from __future__ import annotations

from pathlib import Path


def replace_once(path: str, old: str, new: str) -> None:
    target = Path(path)
    text = target.read_text(encoding="utf-8")
    count = text.count(old)
    if count != 1:
        raise SystemExit(f"{path}: expected one target, found {count}")
    target.write_text(text.replace(old, new, 1), encoding="utf-8")


# 1. Fiscal artifact gate: require a complete monthly tax ledger and explicit IRRF column.
path = "scripts/validate_matrix_top_realistic.py"
old = '''    if tax_path is None:\n        return sorted(set(issues))\n\n    try:\n        recomputed = _curve_recalculated_metrics(\n'''
new = '''    if tax_path is None:\n        return sorted(set(issues))\n\n    required_tax_columns = {"month", "tax_due", "irrf_withheld_month"}\n    if not tax:\n        issues.append("empty_tax_ledger")\n    else:\n        missing_tax_columns = required_tax_columns.difference(tax[0])\n        if missing_tax_columns:\n            issues.append("tax_ledger_missing_columns")\n        try:\n            tax_months = [str(row["month"]) for row in tax]\n            curve_months = sorted({str(row["date"])[:7] for row in curve})\n            if len(tax_months) != len(set(tax_months)):\n                issues.append("tax_ledger_duplicate_month")\n            if tax_months != sorted(tax_months):\n                issues.append("tax_ledger_month_order_mismatch")\n            if sorted(tax_months) != curve_months:\n                issues.append("tax_ledger_month_coverage_mismatch")\n        except (KeyError, TypeError, ValueError):\n            issues.append("invalid_tax_ledger_months")\n\n    try:\n        recomputed = _curve_recalculated_metrics(\n'''
replace_once(path, old, new)
replace_once(
    path,
    '        ledger_irrf = sum(float(row.get("irrf_withheld_month", 0.0) or 0.0) for row in tax)\n',
    '        ledger_irrf = sum(float(row["irrf_withheld_month"]) for row in tax)\n',
)

# 2. Recovery: bind artifacts to the source workflow run and restore its verified data artifact.
path = ".github/workflows/recover-backtest-merge-hardened.yml"
old = '''      - name: Fixar ambiente no commit original dos shards\n        run: |\n          set -euo pipefail\n          SOURCE_DIR="$RUNNER_TEMP/recovery-source"\n          rm -rf "$SOURCE_DIR"\n          git cat-file -e "${CALCULATION_SHA}^{commit}"\n          git worktree add --detach "$SOURCE_DIR" "$CALCULATION_SHA"\n          mkdir -p "$SOURCE_DIR/reports/shards"\n          cp -a reports/shards/. "$SOURCE_DIR/reports/shards/"\n          (\n            cd "$SOURCE_DIR"\n'''
new = '''      - name: Validar identidade do run de origem\n        uses: actions/github-script@v7\n        env:\n          CALCULATION_SHA: ${{ env.CALCULATION_SHA }}\n          SOURCE_RUN_ID: ${{ env.SOURCE_RUN_ID }}\n        with:\n          script: |\n            const sourceRun = await github.rest.actions.getWorkflowRun({\n              owner: context.repo.owner,\n              repo: context.repo.repo,\n              run_id: Number(process.env.SOURCE_RUN_ID),\n            });\n            if (sourceRun.data.head_sha !== process.env.CALCULATION_SHA) {\n              core.setFailed(`source run head_sha ${sourceRun.data.head_sha} != shard calculation SHA ${process.env.CALCULATION_SHA}`);\n              return;\n            }\n            if (sourceRun.data.path !== '.github/workflows/full-matrix-backtest-hardened.yml') {\n              core.setFailed(`unexpected source workflow: ${sourceRun.data.path}`);\n            }\n\n      - name: Baixar dados verificados do run informado\n        uses: actions/download-artifact@v4\n        with:\n          name: verified-market-data-${{ env.SOURCE_RUN_ID }}\n          path: recovery-source-data\n          github-token: ${{ github.token }}\n          repository: ${{ github.repository }}\n          run-id: ${{ env.SOURCE_RUN_ID }}\n\n      - name: Fixar ambiente no commit original dos shards\n        run: |\n          set -euo pipefail\n          SOURCE_DIR="$RUNNER_TEMP/recovery-source"\n          SOURCE_DATA="$GITHUB_WORKSPACE/recovery-source-data"\n          rm -rf "$SOURCE_DIR"\n          git cat-file -e "${CALCULATION_SHA}^{commit}"\n          git worktree add --detach "$SOURCE_DIR" "$CALCULATION_SHA"\n          for required in \\\n            candles \\\n            manifests \\\n            corporate_actions \\\n            universes/fixed_40_2018.json \\\n            quality_reviews.json; do\n            if [ ! -e "$SOURCE_DATA/$required" ]; then\n              echo "::error::artefato de dados do run original incompleto: $required"\n              exit 1\n            fi\n          done\n          rm -rf \\\n            "$SOURCE_DIR/data/candles" \\\n            "$SOURCE_DIR/data/manifests" \\\n            "$SOURCE_DIR/data/corporate_actions"\n          mkdir -p "$SOURCE_DIR/data/universes"\n          cp -a "$SOURCE_DATA/candles" "$SOURCE_DIR/data/candles"\n          cp -a "$SOURCE_DATA/manifests" "$SOURCE_DIR/data/manifests"\n          cp -a "$SOURCE_DATA/corporate_actions" "$SOURCE_DIR/data/corporate_actions"\n          cp "$SOURCE_DATA/universes/fixed_40_2018.json" "$SOURCE_DIR/data/universes/fixed_40_2018.json"\n          cp "$SOURCE_DATA/quality_reviews.json" "$SOURCE_DIR/data/quality_reviews.json"\n          mkdir -p "$SOURCE_DIR/reports/shards"\n          cp -a reports/shards/. "$SOURCE_DIR/reports/shards/"\n          (\n            cd "$SOURCE_DIR"\n'''
replace_once(path, old, new)

# 3. Regression coverage for malformed/empty tax ledgers.
path = "tests/test_realistic_artifact_reconciliation.py"
old = '''\n\nif __name__ == "__main__":\n    unittest.main()\n'''
new = '''\n\n    def test_empty_tax_ledger_is_blocking_even_when_summary_tax_is_zero(self) -> None:\n        with tempfile.TemporaryDirectory() as temporary:\n            payload, curve, trades, cash, tax = self._fixture(Path(temporary))\n            tax.write_text("month,tax_due,irrf_withheld_month\\n", encoding="utf-8")\n            payload["ordinary_income_tax_paid"] = 0.0\n            payload["ordinary_irrf_withheld"] = 0.0\n            payload["outstanding_accrued_tax_liability"] = 0.0\n            issues = _artifact_binding_issues(\n                payload,\n                curve_path=curve,\n                trades_path=trades,\n                cash_path=cash,\n                tax_path=tax,\n            )\n            self.assertIn("empty_tax_ledger", issues)\n            self.assertIn("tax_ledger_month_coverage_mismatch", issues)\n\n    def test_missing_irrf_column_is_fail_closed(self) -> None:\n        with tempfile.TemporaryDirectory() as temporary:\n            payload, curve, trades, cash, tax = self._fixture(Path(temporary))\n            tax.write_text(\n                "month,tax_due\\n2023-12,10\\n2024-01,5\\n",\n                encoding="utf-8",\n            )\n            issues = _artifact_binding_issues(\n                payload,\n                curve_path=curve,\n                trades_path=trades,\n                cash_path=cash,\n                tax_path=tax,\n            )\n            self.assertIn("tax_ledger_missing_columns", issues)\n            self.assertIn("invalid_tax_ledger", issues)\n\n    def test_tax_ledger_must_cover_each_curve_month_exactly_once(self) -> None:\n        with tempfile.TemporaryDirectory() as temporary:\n            payload, curve, trades, cash, tax = self._fixture(Path(temporary))\n            tax.write_text(\n                "month,tax_due,irrf_withheld_month\\n"\n                "2023-12,10,1\\n"\n                "2023-12,5,0\\n",\n                encoding="utf-8",\n            )\n            issues = _artifact_binding_issues(\n                payload,\n                curve_path=curve,\n                trades_path=trades,\n                cash_path=cash,\n                tax_path=tax,\n            )\n            self.assertIn("tax_ledger_duplicate_month", issues)\n            self.assertIn("tax_ledger_month_coverage_mismatch", issues)\n\n\nif __name__ == "__main__":\n    unittest.main()\n'''
replace_once(path, old, new)

# 4. Workflow contract tests now require source-run identity and original verified data.
path = "tests/test_workflow_integrity_contracts.py"
old = '''        self.assertIn("CALCULATION_SHA=", text)\n        self.assertIn('git worktree add --detach "$SOURCE_DIR" "$CALCULATION_SHA"', text)\n        self.assertGreaterEqual(text.count('cd "$SOURCE_DIR"'), 3)\n'''
new = '''        self.assertIn("CALCULATION_SHA=", text)\n        self.assertIn('git worktree add --detach "$SOURCE_DIR" "$CALCULATION_SHA"', text)\n        self.assertIn("sourceRun.data.head_sha !== process.env.CALCULATION_SHA", text)\n        self.assertIn(".github/workflows/full-matrix-backtest-hardened.yml", text)\n        self.assertIn("verified-market-data-${{ env.SOURCE_RUN_ID }}", text)\n        self.assertIn('SOURCE_DATA="$GITHUB_WORKSPACE/recovery-source-data"', text)\n        self.assertIn('cp -a "$SOURCE_DATA/candles" "$SOURCE_DIR/data/candles"', text)\n        self.assertGreaterEqual(text.count('cd "$SOURCE_DIR"'), 3)\n'''
replace_once(path, old, new)
